### ISSUE TITLE
Width of contact me page

### ISSUE THREAD

**Issue by nmitch31** [aormiston1/WebTechWebsite#4]
https://github.com/aormiston1/WebTechWebsite/blob/4255a0abd76aa38d5388c616ac42b5406ec0dd87/contact.html#L17

The position of the form is not in the middle of the screen and the width of the page is longer than the width of the screen.

**Comment by aormiston1** [comment]
fieldset{
    width:center;
    height: 800px;
    font-size: 50px;
}
