### ISSUE TITLE
Adjust discover page

### ISSUE THREAD

**Issue by nmitch31** [aormiston1/WebTechWebsite#6]
https://github.com/aormiston1/WebTechWebsite/blob/4255a0abd76aa38d5388c616ac42b5406ec0dd87/discover.html#L24-L33

Similar to the contact page, the width of the page is wider than the screen. Also, I would suggest aligning the pictures and text so that they are the same size and placed in neat rows and columns.

**Comment by aormiston1** [comment]
max-width: 600px;
    max-height: 650px;
    object-fit:scale-down;
